import { BorrowRecordDTO, ItemDTO, UserDTO } from '../types';

export const INITIAL_USERS: UserDTO[] = [
  {
    userId: 'U101',
    name: 'Sarah Jenkins',
    username: 'sarah_j',
    email: 'sarah.jenkins@example.com',
    phone: '+1 (555) 234-5678',
    locality: 'Maple Heights',
    ratingAverage: 4.8,
    ratingCount: 12,
    finesOwed: 0.0,
    finesPaid: 5.0,
    joinedDate: '2026-06-15',
    isVerified: true,
    emailVerified: true,
    idVerificationStatus: 'VERIFIED',
    idDocumentType: 'Driver License',
    verificationDate: '2026-06-16',
    extraProofDetails: 'Homeowner association membership verified',
    securityPledgeSigned: true
  },
  {
    userId: 'U102',
    name: 'Michael Chen',
    username: 'mchen',
    email: 'mchen@example.com',
    phone: '+1 (555) 345-6789',
    locality: 'Oakridge District',
    ratingAverage: 4.9,
    ratingCount: 19,
    finesOwed: 0.0,
    finesPaid: 0.0,
    joinedDate: '2026-05-10',
    isVerified: true,
    emailVerified: true,
    idVerificationStatus: 'VERIFIED',
    idDocumentType: 'Passport',
    verificationDate: '2026-05-11',
    extraProofDetails: 'Workplace identity & community lease verified',
    securityPledgeSigned: true
  },
  {
    userId: 'U103',
    name: 'Priya Sharma',
    username: 'priya_s',
    email: 'priya.sharma@example.com',
    phone: '+1 (555) 456-7890',
    locality: 'Sunnyvale Community',
    ratingAverage: 4.7,
    ratingCount: 9,
    finesOwed: 5.0,
    finesPaid: 15.0,
    joinedDate: '2026-07-01',
    isVerified: false,
    emailVerified: true,
    idVerificationStatus: 'PENDING',
    idDocumentType: 'Utility Bill'
  },
  {
    userId: 'U104',
    name: 'David Miller',
    username: 'david_m',
    email: 'david.miller@example.com',
    phone: '+1 (555) 567-8901',
    locality: 'Riverside Green',
    ratingAverage: 5.0,
    ratingCount: 6,
    finesOwed: 0.0,
    finesPaid: 0.0,
    joinedDate: '2026-08-20',
    isVerified: true,
    emailVerified: true,
    idVerificationStatus: 'VERIFIED',
    idDocumentType: 'Driver License',
    verificationDate: '2026-08-21',
    extraProofDetails: 'Local electric utility bill verified',
    securityPledgeSigned: true
  },
];

export const INITIAL_ITEMS: ItemDTO[] = [
  {
    itemId: 'I201',
    title: 'Bosch Hammer Drill 18V Kit',
    category: 'Tool',
    description: 'Heavy duty brushless cordless hammer drill with 2 lithium batteries and 14-piece masonry drill bit set.',
    ownerId: 'U101',
    ownerName: 'Sarah Jenkins',
    locality: 'Maple Heights',
    isAvailable: true,
    borrowDurationDays: 3,
    dailyFineRate: 5.0,
    dateAdded: '2026-09-01',
    condition: 'Like New',
  },
  {
    itemId: 'I202',
    title: '12.5ft Aluminium Telescopic Extension Ladder',
    category: 'Tool',
    description: 'Compact telescoping ladder with non-slip rungs. Extends up to 3.8 meters, holds up to 150kg.',
    ownerId: 'U102',
    ownerName: 'Michael Chen',
    locality: 'Oakridge District',
    isAvailable: true,
    borrowDurationDays: 3,
    dailyFineRate: 5.0,
    dateAdded: '2026-09-03',
    condition: 'Good',
  },
  {
    itemId: 'I203',
    title: 'Karcher K4 Electric Pressure Washer (1800 PSI)',
    category: 'Tool',
    description: 'High-pressure water blaster with dirt blaster nozzle, 25ft high-pressure hose, and detergent tank.',
    ownerId: 'U101',
    ownerName: 'Sarah Jenkins',
    locality: 'Maple Heights',
    isAvailable: false,
    borrowDurationDays: 3,
    dailyFineRate: 5.0,
    dateAdded: '2026-09-05',
    condition: 'Good',
  },
  {
    itemId: 'I204',
    title: 'Drive Medical Lightweight Folding Wheelchair',
    category: 'MedicalEquipment',
    description: 'Comfortable 18-inch seat with swing-away footrests, padded armrests, and dual rear brakes. Foldable for car trunks.',
    ownerId: 'U103',
    ownerName: 'Priya Sharma',
    locality: 'Sunnyvale Community',
    isAvailable: true,
    borrowDurationDays: 7,
    dailyFineRate: 10.0,
    dateAdded: '2026-09-06',
    condition: 'Like New',
  },
  {
    itemId: 'I205',
    title: 'Adult Adjustable Underarm Crutches (Pair)',
    category: 'MedicalEquipment',
    description: 'Anodized aluminum crutches adjustable for heights 5ft 2in to 5ft 10in with ergonomic cushioned grips.',
    ownerId: 'U104',
    ownerName: 'David Miller',
    locality: 'Riverside Green',
    isAvailable: true,
    borrowDurationDays: 7,
    dailyFineRate: 10.0,
    dateAdded: '2026-09-08',
    condition: 'Good',
  },
  {
    itemId: 'I206',
    title: 'Philips Respironics Compressor Nebulizer System',
    category: 'MedicalEquipment',
    description: 'Compact aerosol medication compressor with reusable side-stream mouthpiece and pediatric mask.',
    ownerId: 'U103',
    ownerName: 'Priya Sharma',
    locality: 'Sunnyvale Community',
    isAvailable: true,
    borrowDurationDays: 7,
    dailyFineRate: 10.0,
    dateAdded: '2026-09-10',
    condition: 'Like New',
  },
  {
    itemId: 'I207',
    title: 'Anker Nebula Solar Portable Projector 1080p',
    category: 'Electronics',
    description: 'Full HD 400 ANSI lumen smart outdoor projector with built-in battery (3 hours), HDR10, and HDMI input.',
    ownerId: 'U102',
    ownerName: 'Michael Chen',
    locality: 'Oakridge District',
    isAvailable: true,
    borrowDurationDays: 5,
    dailyFineRate: 8.0,
    dateAdded: '2026-09-11',
    condition: 'Like New',
  },
  {
    itemId: 'I208',
    title: 'Sony Alpha a6400 Mirrorless Camera + 16-50mm',
    category: 'Electronics',
    description: '24.2MP 4K camera with lightning fast autofocus, flip screen, 64GB SD card, and 2 extra batteries with dual charger.',
    ownerId: 'U104',
    ownerName: 'David Miller',
    locality: 'Riverside Green',
    isAvailable: true,
    borrowDurationDays: 5,
    dailyFineRate: 8.0,
    dateAdded: '2026-09-12',
    condition: 'Like New',
  },
  {
    itemId: 'I209',
    title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
    category: 'Book',
    description: 'Classic Gang of Four (GoF) engineering book covering creational, structural, and behavioral design patterns.',
    ownerId: 'U101',
    ownerName: 'Sarah Jenkins',
    locality: 'Maple Heights',
    isAvailable: true,
    borrowDurationDays: 14,
    dailyFineRate: 1.0,
    dateAdded: '2026-09-14',
    condition: 'Good',
  },
  {
    itemId: 'I210',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    category: 'Book',
    description: 'By Robert C. Martin. Best practices, meaningful naming, refactoring guidelines, and unit testing fundamentals.',
    ownerId: 'U102',
    ownerName: 'Michael Chen',
    locality: 'Oakridge District',
    isAvailable: false,
    borrowDurationDays: 14,
    dailyFineRate: 1.0,
    dateAdded: '2026-09-15',
    condition: 'Fair',
  }
];

export const INITIAL_BORROW_RECORDS: BorrowRecordDTO[] = [
  {
    recordId: 'R301',
    itemId: 'I203',
    itemTitle: 'Karcher K4 Electric Pressure Washer (1800 PSI)',
    category: 'Tool',
    borrowerId: 'U102',
    borrowerName: 'Michael Chen',
    lenderId: 'U101',
    lenderName: 'Sarah Jenkins',
    borrowDate: '2026-09-17',
    dueDate: '2026-09-20',
    returnDate: null,
    status: 'OVERDUE',
    daysLate: 1,
    fineAmount: 5.0,
    finePaid: false,
    pickupNote: 'Driveway power washing before the autumn leaves fall.',
    pickupSlot: 'Evening 6:00 PM',
    borrowerMobile: '+1 (555) 345-6789',
    extraProofType: 'Driver License',
    extraProofNote: 'DL-9821 verified on exchange'
  },
  {
    recordId: 'R302',
    itemId: 'I210',
    itemTitle: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    category: 'Book',
    borrowerId: 'U103',
    borrowerName: 'Priya Sharma',
    lenderId: 'U102',
    lenderName: 'Michael Chen',
    borrowDate: '2026-09-18',
    dueDate: '2026-10-02',
    returnDate: null,
    status: 'ACTIVE',
    daysLate: 0,
    fineAmount: 0.0,
    finePaid: false,
    pickupNote: 'Reading chapter on function decomposition.',
    pickupSlot: 'Porch drop-off',
    borrowerMobile: '+1 (555) 456-7890',
    extraProofType: 'Utility Bill',
    extraProofNote: 'Power bill confirmed address'
  }
];
